version: '3'
services:
    db:
        image: "mysql:5.7"
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=azc
            - MYSQL_USER=azc
            - MYSQL_PASSWORD=azc
        volumes:
            - sqldata:/var/lib/mysql
            - ./dumps:/media
        networks:
            - back

    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin/phpmyadmin
        ports:
            - 0.0.0.0:8090:80
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: root
        networks:
            - front
            - back

    nodejs:
        build: docker/nodejs
        volumes:
            - ./src:/code
        working_dir: /code/wp-content/themes/azc

    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./src:/code
            - ./docker/nginx/web.conf:/etc/nginx/conf.d/default.conf
        working_dir: /code
        links:
            - php
        networks:
            - front
            - back

    php:
        build: docker/php
        working_dir: /code
        volumes:
            - ./src:/code
        depends_on:
            - db
        networks:
            - back

networks:
    front:
    back:
volumes:
    sqldata:

